### ISSUE TITLE
Use Persistent Mode for Remote Desktop Portal Autotype

### ISSUE THREAD

**Issue by mabequinho** [quexten/goldwarden#150]
Any method to bypass this "Allow Remote Interaction" dialog?

Fedora Silverblue 40, Gnome 46

![image](https://github.com/quexten/goldwarden/assets/46428150/59baf80c-dd88-4e8b-8c9a-9d185f02943c)

**Comment by quexten** [comment]
Ok so right now the only auto-type method implemented is the remote desktop portal (which really is meant for remote desktop, but there is no auto-type portal just yet). 
I think we should be able to cache the remote desktop session, so that the prompt only turns up once on boot, but I haven't looked that deep into it yet.

Besides that we can implement more auto-type methods of course, some of which don't work on gnome, some of which require an external (outside flatpak) daemon that runs as a user part of the input group, or root.

**Comment by quexten** [comment]
Implemented in #177, haven't tested enough yet to know whether it persists through system restarts, but it does persist through application restarts, at least on gnome/xdg-desktop-portal-gnome.

**Comment by quexten** [comment]
Ok, tested on a development flatpak build, and it seems to persist through device restarts too, so permission granting should only be required the first time. Nice.

I will keep the issue open until this change is included in a flathub release, and has had some testing.

**Comment by quexten** [comment]
Released 0.2.15 with this included. Please test :)

**Comment by mabequinho** [comment]
Working flawlessly across reboots. Gnome 46 Fedora 40.
