### ISSUE TITLE
Autotype shortcut should not need explicit approval beyond polkit prompt

### ISSUE THREAD

**Issue by mufeedali** [quexten/goldwarden#52]
When using the global autotype shortcut, we shouldn't need to approve the listing of credentials.

**Comment by ThatOneCalculator** [comment]
+1 on this. Especially since it ends up being two different popups before I can even get to autofilling.

First popup:
![image](https://github.com/quexten/goldwarden/assets/44733677/9de16c71-469f-46b1-8f55-fa4a0ec6e27b)

Second popup:
![image](https://github.com/quexten/goldwarden/assets/44733677/3fcb2b71-933a-4438-8dde-4cdcc41cd38a)

Third popup (the actual window I need):
![image](https://github.com/quexten/goldwarden/assets/44733677/cc0e4297-67f8-412b-a282-0b42b6f6e0c1)

**Comment by quexten** [comment]
Thanks, this is indeed too many prompts. It's always a balance between fine grained security, and annoying the user too much. In this case I agree. I'll check on how to improve this!

**Comment by ThatOneCalculator** [comment]
I know that a lot of apps like VSCode use the system's keyring for secrets and whatnot

**Comment by mufeedali** [comment]
> use the system's keyring

That's not good enough I think. I would just want the second prompt to not be there when using the autotype feature. Everything else can remain the same.

The question would probably be, how to do that? If I'm understanding correctly, the autotype is from Python and the approval prompt is from Go. So there's no guarantee that a request from the autotype can't be spoofed.

**Comment by quexten** [comment]
Yeah, I agree with what @mufeedali says. Storing things is the keyring is too open for Goldwarden's security model.

I think what could work is instead of creating a new socket every time, a permanent unix socket is established that serves as the authentication. No secrets needed that can be stolen from python. I'll have to play around with this a bit.

**Comment by quexten** [comment]
Fixed on latest dev branch, but still requires testing. Will be in 0.2.11.

**Comment by c4tz** [comment]
Hey @quexten , I just noticed the same behaviour when using Goldwarden to unlock the Chromium browser extension.

The steps for me are exactly the same as in @ThatOneCalculator's comment above with `0.2.13-1` from the AUR:
1. Unlock polkit by entering password (or using biometrics, if configured)
2. Approve message by Goldwarden
3. -> Unlocked browser extension

Is there any way I could bypass that approval?

**Comment by quexten** [comment]
No way to bypass, but that behaviour should probably be simplified. I have not had time to triage it yet, but it also happens on my end.

https://github.com/quexten/goldwarden/issues/142

**Comment by c4tz** [comment]
Ah, thank you for creating the new issue with extended problem description/thoughts. I will subscribe to it right away! :)
