### ISSUE TITLE
Biometrics unlock not working with Brave

### ISSUE THREAD

**Issue by mufeedali** [quexten/goldwarden#54]
It is working as intended with Firefox, but not with Brave.

It says:
"Browser integration is not set up in the Bitwarden desktop application. Please set it up in the settings within the desktop application."

The NativeMessagingHosts directory is present and had a 1Password-generated json file. But nothing from Bitwarden.

**Comment by quexten** [comment]
What's the directory for nativemessaginghosts of brave for you? There was a recent issue after which I added support for brave:
https://github.com/quexten/goldwarden/blob/e15cee5aa92749b395960498dd069b8794025e68/browserbiometrics/main.go#L13-L22

**Comment by mufeedali** [comment]
`~/.config/BraveSoftware/Brave-Browser/`

The directory is correct. I don't really understand why it doesn't work...

I get the message "Native messaging host directory already exists".
But I dont get the "Found chrome-like browser" message for Brave.

**Comment by mufeedali** [comment]
I copied the folder from Chrome to Brave and it works now

**Comment by quexten** [comment]
Not sure why the setup did not work, but since it seems to work for you, I'm closing the issue.

**Comment by mufeedali** [comment]
Yep, i did get it working for the most part. It still didn't work with Brave running as a flatpak though, even after doing the manual steps (but into the flatpak folder ofc).

**Comment by quexten** [comment]
If the browser is running as a flatpak, I don't think this is supported. As in, ipc in general. Anything running inside the flatpak sandbox has no way to communicate to the outside, so the socket won't work, and we can't even change to another ipc communication mechanism like dbus, because that's sandboxed too. _An ugly hack could be to run goldwarden on a localhost network socket, but I'm not sure that's a good idea._

You might have luck if you change the flatpak's sandboxing permissions with something like flatseal.

Anyway, for more info on this see here:
https://github.com/quexten/bw-bio-handler/issues/6
and
https://github.com/flatpak/xdg-desktop-portal/issues/655
