### ISSUE TITLE
Explain Pin & Biometric behaviour and Make it Conifgurable

### ISSUE THREAD

**Issue by woolmonkey** [quexten/goldwarden#92]
Sometimes I get asked the pin other times I get asked my password.  
Also is it there a way we can adjust the timing for the pin.  It asks for it a lot or at least seams to for me.

**Comment by quexten** [comment]
So the behaviour was:
When your vault is "locked", you need your pin. 
When your vault is "unlocked", you need password/biometrics, if that fails, you need your pin.

Locking happens on screensaver or if you manually run lock.

#113 Introduces an authentication cache, so that even when locked, you can use your password/biometrics. Only when actually restarting the daemon, it will ask you for the pin again.

Added a note in the wiki here:
https://github.com/quexten/goldwarden/wiki/Security#locking-behaviour

**Comment by quexten** [comment]
>  Also is it there a way we can adjust the timing for the pin. It asks for it a lot or at least seams to for me.

Just to be clear, only the calling terminal will be remembered for SSH. I.e if you switch to another terminal, this will have to authenticate again when using SSH. The time that one application will be remembered has been adjusted up to 1 hour in the latest main branch.

**Comment by quexten** [comment]
Done with v0.2.12
